name: Example Workflow

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install
        run: npm install
        working-directory: packages/client-ts
      - name: Lint
        uses: a-b-r-o-w-n/eslint-action@echo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: packages/client-ts/src/**/*
          working-directory: packages/client-ts
          quiet: false
