name: Example Workflow

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # - name: npm install
      #   run: npm install
      #   working-directory: packages/client-ts
      - name: Test bash
        run: node test-echo.js
      # - name: Lint
      #   run: npm run lint -- -f ./test-formatter.js
      #   working-directory: packages/client-ts
        # uses: a-b-r-o-w-n/eslint-action@esbuild
        # with:
        #   repo-token: ${{ secrets.GITHUB_TOKEN }}
        #   files: packages/client-ts/src/**/*
